# Generated by Django 4.2.7 on 2024-01-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
                ('firstName', models.CharField(max_length=150)),
                ('dateField', models.DateTimeField()),
                ('image', models.ImageField(upload_to='images/')),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
